[workspace]
resolver = "2"
members = ["rayforce-sys", "rayforce"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["RayforceDB"]
repository = "https://github.com/RayforceDB/rayforce-rs"
rust-version = "1.74"

[workspace.dependencies]
rayforce-sys = { path = "rayforce-sys", version = "0.1.0" }
