//! Raw FFI bindings to the RayforceDB v2 core (`librayforce`).
//!
//! Generated by `bindgen` from `wrapper.h` (the public `rayforce.h` plus a few
//! hand-declared internal symbols). This crate is `unsafe` and 1:1 with the C
//! ABI; use the safe `rayforce` crate instead.
//!
//! The header's function-like macros (`ray_type`, `ray_len`, `ray_data`,
//! `RAY_IS_ERR`, `RAY_IS_NULL`, …) are not emitted by bindgen — the safe crate
//! reimplements them in Rust against the generated [`ray_t`] layout.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Vendored KDB+ IPC client (csrc/kdb_ipc.c). Not part of the engine bindings;
// hand-declared here until it moves into the engine proper.
extern "C" {
    /// Connect + KDB+ handshake. Returns a connection slot (>= 0) or -1.
    pub fn rkdb_connect(host: *const ::std::os::raw::c_char, port: ::std::os::raw::c_int) -> i64;
    /// Send a rayforce object (typically a RAY_STR query) and return the decoded
    /// response, or a RAY_ERROR object on failure (never null).
    pub fn rkdb_send(slot: i64, msg: *mut ray_t) -> *mut ray_t;
    /// Close a connection slot (no-op if invalid).
    pub fn rkdb_close(slot: i64);
}
