site_name: Rayforce-RS
site_description: Convenient, high-performance Rust bindings for RayforceDB v2
repo_url: https://github.com/RayforceDB/rayforce-rs
repo_name: GitHub

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.svg
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Outfit
    code: JetBrains Mono
  logo: assets/logo_light_full.svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RayforceDB/rayforce-rs
    - icon: fontawesome/brands/rust
      link: https://crates.io/crates/rayforce

copyright: Copyright &copy; 2026 RayforceDB

plugins:
  - offline
  - search:
      separator: '[\s​\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - admonition
  - footnotes

extra_css:
  - https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&display=swap
  - css/custom.css
  - css/hero.css

nav:
  - Home: index.md
  - Get Started:
      - Overview: content/get-started/overview.md
      - Installation: content/get-started/installation.md
      - Technical Details: content/get-started/technical-details.md
  - Documentation:
      - Overview: content/documentation/overview.md
      - Data Types:
          - Overview: content/documentation/data-types/overview.md
          - Values & Conversions: content/documentation/data-types/values.md
          - Integers: content/documentation/data-types/integers.md
          - Float: content/documentation/data-types/float.md
          - Boolean: content/documentation/data-types/boolean.md
          - Symbol: content/documentation/data-types/symbol.md
          - String: content/documentation/data-types/string.md
          - Temporal: content/documentation/data-types/temporal.md
          - GUID: content/documentation/data-types/guid.md
          - Vector: content/documentation/data-types/vector.md
          - List: content/documentation/data-types/list.md
          - Dict: content/documentation/data-types/dict.md
          - Functions: content/documentation/data-types/functions.md
      - Table:
          - Overview: content/documentation/table/overview.md
          - Create: content/documentation/table/create.md
          - Access Values: content/documentation/table/access-values.md
          - Transform: content/documentation/table/transform.md
          - Save and Fetch: content/documentation/table/save-and-fetch.md
          - Splayed and Parted: content/documentation/table/splayed-and-parted.md
      - Query Guide:
          - Overview: content/documentation/query-guide/overview.md
          - Expressions: content/documentation/query-guide/expressions.md
          - Select: content/documentation/query-guide/select.md
          - Where: content/documentation/query-guide/where.md
          - Group By: content/documentation/query-guide/group-by.md
          - Order By: content/documentation/query-guide/order-by.md
          - Update: content/documentation/query-guide/update.md
          - Insert: content/documentation/query-guide/insert.md
          - Upsert: content/documentation/query-guide/upsert.md
          - Joins: content/documentation/query-guide/joins.md
      - IPC: content/documentation/ipc.md
      - Serialization: content/documentation/serialization.md
  - Changelog: content/CHANGELOG.md
  - License: content/license.md
